### ISSUE TITLE
It doesn't work in Chrome

### ISSUE THREAD

**Issue by Borisboky** [open-eid/chrome-token-signing#105]
I'm trying to use it in on MacOS High Sierra (v 10.13.3) on Chrome, but it doesn't work.

I get an error as follows:

![screen shot 2018-03-22 at 11 13 57](https://user-images.githubusercontent.com/13819165/37764542-3ab14900-2dc2-11e8-85dd-4179fa8bf463.png)

I followed install instructions:

1. Installed Belgian eID driver software
2. Installed Chrome Token Signing extension
3. Restarted Chrome
4. Inserted smart card to the reader
5. Tried to test it on https://hwcrypto.github.io/hwcrypto.js/sign.html

But I'm getting the error above.

**Comment by metsma** [comment]
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L90-L163
You need match ATR and your card middleware path

**Comment by Borisboky** [comment]
Sorry, but I do not understand what I need to do.
