### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by amaccuish** [open-eid/chrome-token-signing#108]
Trying to test on the upcoming Ubuntu 18.04 LTS. Token signing fails with the following kernel error:

> kernel: traps: chrome-token-si[27145] general protection ip:7f704bf51ca5 sp:7fff3cfdeba8 error:0 in libcrypto.so.1.0.0[7f704be37000+219000]

**Comment by metsma** [comment]
Seems like 18.04 qt comes with openssl 1.1 and plugin is compiled with openssl 1.0.
Master has removed openssl dependency.
We need recompile last version with openssl 1.1 on 18.04

**Comment by amaccuish** [comment]
Ye recompiled it and it was all fine, though it did seem to get stuck at one point and started consuming 100% CPU, if I can track it down I'll open a new ticket

**Comment by amaccuish** [comment]
Does anyone know when bionic packages will be available from the repo?

**Comment by metsma** [comment]
Official binaries released https://installer.id.ee/media/ubuntu/
