### ISSUE TITLE
Linux installation of token signing requires ld but it's not a dependency

### ISSUE THREAD

**Issue by TaaviE** [open-eid/chrome-token-signing#138]
In the script `/usr/bin/esteid-update-nssdb` at line 29 the installation script fails with the error `ld: command not found`, I solved it by installing `gcc-8` manually, but if it's required like that to enable ID-card functionality in Chrome(/ium) then it should be the package's dependency.

**Comment by metsma** [comment]
This is not related to chrome token signing.
should be fixed with https://github.com/open-eid/linux-installer/pull/60
