### ISSUE TITLE
having trouble making it work on openSuSE 15.0

### ISSUE THREAD

**Issue by tari3x** [open-eid/chrome-token-signing#139]
I added and enabled both the "PKCS11 loader" plugin and the "Token signing" plugin to firefox on openSuSE. When trying to log into eesti.ee, the card is not being read, all I get is
"Kas Teie ID-kaart on kaardilugejasse sisestatud?"

How do I debug this? Is OpenSuSE supported at all? 

I also tried installing packages from kentaur, but those seem to make incorrect assumptions about firefox extension paths, so I gave up.

**Comment by metsma** [comment]
This component is only for signing. You need opensc-pkcs11 driver and [open-eid/firefox-pkcs11-loader](/open-eid/firefox-pkcs11-loader)
