### ISSUE TITLE
eesti.ee fails with no_implementation when trying to sign an application

### ISSUE THREAD

**Issue by tari3x** [open-eid/chrome-token-signing#140]
Using OpenSuSE 15.0. I installed chrome-token-signing and pkcs11-firefox-loader. Got into eesti.ee in firefox by providing both pins, so the authentication part works.

Now I am trying to sign an application in https://www.eesti.ee/portaal/!rrteenus.avaldused?aliik=A01

When I click 'Edasi allkirjastamisele', nothing happens.

JS console shows 'TypeError: this.errorHandler is not a function'. (That's bug number 1, perhaps you know who to report eesti.ee bugs to?)

With some javascript tracing, the error turns out to be hwcrypto.NO_IMPLEMENTATION. What do I do to debug this further?

Note that both PIN1 and PIN2 show as having been loaded in Settings->Security Devices.

**Comment by Counter178** [comment]
'TypeError: this.errorHandler is not a function' - signing pop-up canceled. Check pop-ups.

**Comment by tari3x** [comment]
I'm not sure what you mean by 'check pop-ups'. I am pretty sure there was no pop-up at that point.

If the error always happens due to hitting 'cancel' on the pop-up, would it be possible to clarify the error?

**Comment by Counter178** [comment]
Debugging - https://github.com/open-eid/chrome-token-signing/wiki/DeveloperTips
And to clarify that components are meant to work for Ubuntu only.

**Comment by tari3x** [comment]
So other linux distros are not supported? Would it be hard to support them? After all, this is just a firefox extension, so shouldn't depend on what distro I use?

**Comment by Counter178** [comment]
> So other linux distros are not supported? Would it be hard to support them? After all, this is just a firefox extension, so shouldn't depend on what distro I use?

https://github.com/open-eid/**chrome**-token-signing/wiki

**Comment by tari3x** [comment]
I think the reason you point me to that page is that it suggests that three is a platform specific component required to use the card. Note, however, that I was able to use the card for authentication, so card use, certificate selection, and pin entry are already supported on my system. 

Next time I run into the same problem, I'll try logging as described in the developer tips. Fine to close for now.
