### ISSUE TITLE
Supporting for A1 Certificate

### ISSUE THREAD

**Issue by johnnywiller** [open-eid/chrome-token-signing#142]
Hello, it seems that the project doesn't support local file certificate (A1 type), right?

What is the alternative to look for all available certificates Token plus Browser Installed or Local Files?

Thanks in advance guys!

**Comment by metsma** [comment]
Software certificates are not supported and will not be.
You can modify code and disable checks and make own build
https://github.com/open-eid/chrome-token-signing/blob/master/host-windows/NativeCertificateSelector.cpp#L68
https://github.com/open-eid/chrome-token-signing/blob/master/host-windows/NativeCertificateSelector.cpp#L55

Shoftware PKCS11 lib
https://github.com/opendnssec/SoftHSMv2
