### ISSUE TITLE
how to uninstall this extension from chrome?

### ISSUE THREAD

**Issue by ccding** [open-eid/chrome-token-signing#143]

**Comment by ccding** [comment]
uninstalled and reinstalled chrome: problem solved.

**Comment by fmmalta** [comment]
This does not work

**Comment by Counter178** [comment]
> This does not work

Run the installer again and "uninstall"

**Comment by fmmalta** [comment]
> > This does not work
> 
> Run the installer again and "uninstall"

I ended up unnistalling my OS...

**Comment by muhuk** [comment]
I am using **Debian Linux** and the chrome extension does not work for me (but Firefox one works fine).

I have followed following steps to disable the chrome extension:

* Change `/usr/share/chrome-token-signing/ee.ria.chrome-token-signing.policy.json` file as below:
  ```
  {
    "ExtensionInstallWhitelist": [
      "ckjefchnfjhjfedoccjbhjpbncimppeg"
    ]
  }
  ```
  (Whitelisting should be fine.  Do not delete this file because it has 3 symlinks and the will be broken)
* Edit `~/.config/google-chrome/Default/Preferences` and remove all `"ckjefchnfjhjfedoccjbhjpbncimppeg"` keys.  This is a JSON file so you might want to use a JSON aware editor.  I removed all such keys since I don't know what each of them meant.

Don't forget to backup files you change.

This solution enabled me to disable the extension.  If in the future it starts working, it looks like I will also be able to choose specific sites that it has access to.

-----

I hope the development team re-evaluate the decision to force install the plugin.  Target audience should have enough technical skills to be able to install and manage a browser extension.

**Comment by aladagemre** [comment]
I am using MacOS.

To get id of the Managed by the organization warning, [these instuctions](https://support.google.com/chrome/thread/8777356?msgid=9500198) helped. System Preferences -> Profiles -> Remove the Estonian profile. This will clear chrome://policy/ content.

But I could not remove the extension. Removing lines from json or deleting extension folder did not help. It reinstalls the extension automatically.

**Comment by maesenka** [comment]
I'm also using MacOs and cannot find a way to uninstall this plugin. 

I find that totally unacceptable, and will flag this as an abuse on the Chrome Webstore.

**Comment by Counter178** [comment]
sudo profiles -R -p ee.ria.chrome-token-signing -u 56789
sudo rm –rf  /Library/Application\ Support/Google/Chrome/External\ Extensions/ckjefchnfjhjfedoccjbhjpbncimppeg.json \  

"Target audience should have enough technical skills to be able to install and manage a browser extension."

Unfortunate as it is, they don't. Imagine feedback on scale 10:1 when people desire automatic install/enable of extension.

**Comment by martinpaljak** [comment]
I guess folks would not be that unhappy if the README provided clear instructions on how to uninstall this.

**Comment by metsma** [comment]
Seems that sometimes it does not help if you remove enterprise policy

https://www.howtogeek.com/410270/how-to-remove-a-chrome-extension-installed-by-enterprise-policy-on-windows/
> Start Fresh
> If you still see an extension that’s “Installed by Enterprise Policy,” then there’s only one last thing > you can do: burn your computer and start fresh.

**Comment by muhuk** [comment]
After an update, this extension made a comeback again and hijacked my chrome.

This time these two commands worked:

```bash
sudo rm /etc/opt/chrome/policies/managed/ee.ria.chrome-token-signing.policy.json
sudo rm /usr/share/google-chrome/extensions/ckjefchnfjhjfedoccjbhjpbncimppeg.json
```

I am using Debian/Linux.

As usual; don't forget to make copies of anything you delete.

**Comment by metsma** [comment]
You can alway uninstall the policy and extension.
Apt remove chrome-token-signing
Apt remove token-signing-chrome

**Comment by muhuk** [comment]
I don't want to uninstall the extension altogether.  I want to be able to disable it in chrome. (I use firefox for signing so I still need it installed)

**Comment by metsma** [comment]
You can keep still the token-signing-firefox extension

**Comment by muhuk** [comment]
@metsma looks like it is possible to remove chrome bits but keep the firefox plugin.  Thanks.

I still wish the chrome extension could be managed by the user, I still think this is not the user friendly way to go.

By the way you need to remove `open-eid` and carefully mark DigiDoc client packages to avoid deletion. I haven't executed the uninstall yet, but this isn't a convenient way.

![image](https://user-images.githubusercontent.com/40178/89129236-68058880-d504-11ea-8f25-bd0e063af0fd.png)

There goes nothing...

**Comment by muhuk** [comment]
OK, I can confirm above method works.  Thanks again @metsma !

**Comment by ademidun** [comment]
Originally posted this question here (https://github.com/open-eid/chrome-token-signing/issues/126#issuecomment-693143255) since I don't know which thread this belongs in.

Ccan someone please answer my question in very simple terms.


**How can I completely uninstall this extension on my MacOS?**

**Comment by metsma** [comment]
sudo profiles remove --identifier ee.ria.chrome-token-signing
sudo rm -rf \
        /Library/Google/Chrome/NativeMessagingHosts/chrome-token-signing.app \
        /Library/Google/Chrome/NativeMessagingHosts/ee.ria.esteid.json \
        /Library/Application\ Support/Google/Chrome/External\ Extensions/ckjefchnfjhjfedoccjbhjpbncimppeg.json \
        /Library/Application\ Support/Mozilla/NativeMessagingHosts/ee.ria.esteid.json

**Comment by Counter178** [comment]
Instructions are available here: https://github.com/open-eid/chrome-token-signing/wiki/Extension-removal.

**Comment by kohtala** [comment]
So in summary, the msiexec /x does not work on the .msi, but you have to launch the msi file and select remove from the UI.
