### ISSUE TITLE
The chrome extension comes disabled

### ISSUE THREAD

**Issue by kurtuluso** [open-eid/chrome-token-signing#163]
I installed the chrome extension to several computers.
In some cases, I see the chrome extension disabled however it is not possible to enable it.
Then I open the extension in chrome web store and a message appears like "Your extension is disabled, click to enable". I click it and then it becomes enabled.

This is the only way to enable the extension.

Why can't I enable it in the extension settings but in the chrome web store? 

Thanks

**Comment by metsma** [comment]
Seems like chrome loses some times verified_contents.json files
https://bugs.chromium.org/p/chromium/issues/detail?id=807883

**Comment by JavaDeveloper08** [comment]
Hi @kurtuluso, how can i use this extension by using turkish akis card. I installed digidoc4 client to my pc. But it says "No card in card reader". But I am using my card via application of formal sites. I saw the commits that include Akis Card support codes which added by you. How can i implement this ?
Could you help me?

**Comment by kurtuluso** [comment]
@JavaDeveloper08 As far as I know digidoc looks for a citizen (estonia) card.
Check https://hwcrypto.github.io/demo/ to test your card

**Comment by JavaDeveloper08** [comment]
@kurtuluso thanks for your reply,

I tried it, but I am getting certificate error. 

sign() clicked on Wed, 04 Nov 2020 14:44:16 GMT
Signing SHA-256: 413140d54372f9baf481d4c54e2d5c7bcf28fd6087000280e07976121dd54af2
Debug: hwcrypto.js 0.0.11 with Chrome native messaging extension 0.0.30/1.1.2.520
getCertificate() failed: Error: no_certificates

**Comment by kurtuluso** [comment]
@JavaDeveloper08 
Well, It may not be the best place for investigation though.
What is the OS? It is absolutely working with windows.
There are some problems in general with OSX.
Check the log as written in https://github.com/open-eid/chrome-token-signing/wiki/DeveloperTips

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the active development and management of the Token Signing component has ended due to the transition to the new web authentication and signing solution (Web eID).
We are happy to accept your proposals in the new Web eID project repository: https://github.com/web-eid.
