### ISSUE TITLE
Upon installing Token Signing Chrome Extension I was redirected here and now what?

### ISSUE THREAD

**Issue by marsrobertson** [open-eid/chrome-token-signing#166]
I need to install: https://github.com/open-eid/chrome-token-signing/releases

![image](https://user-images.githubusercontent.com/44369284/84007271-08f22000-a968-11ea-8c42-7e2d19c8f1cd.png)

There is no release marked as Mac.

Shall I use:
`chrome-token-signing_1.1.2.517-1804.tar.xz`
Or:
`chrome-token-signing_1.1.2.517.orig.tar.xz`

"orig" sounds more legit than "1804" build number, never seen "xz" extension before but luckily it is some version of ".zip" and my computer unpacks it...

### I have no idea where to click, I have no idea what to do?

![image](https://user-images.githubusercontent.com/44369284/84007464-60908b80-a968-11ea-8f3c-2d327d68ee43.png)

### Ideally

Distribute as `.exe` for Windows, `.dmg` for Mac and sign the file so that built-in security is not throwing security warnings...

**Comment by marsrobertson** [comment]
It works for me, just installed things from here: https://installer.id.ee/?lang=eng

I was just confused that at some point I was redirected to this repo and didn't know what to do...

**Comment by Counter178** [comment]
Future forwarding to https://installer.id.ee/?lang=eng will be in order. Github repo is meant for developers.
