### ISSUE TITLE
MacOS does not log as detailed in wiki

### ISSUE THREAD

**Issue by maagiline** [open-eid/chrome-token-signing#176]
Referring to this page in wiki: https://github.com/open-eid/chrome-token-signing/wiki/DeveloperTips

In my MacOS machine, I am trying to read debug logs from ~/tmp/chrome-signing.log, as detailed in wiki. However, nothing is logged in this location.

The logs are written to the specified XCode debug location, as detailed in the end of the wiki page. I am not, however, using XCode for anything. Is the wiki misleading, or is it a question of my machine's configuration?

MacOS Catalina 10.15.6 (19G2021)
Chrome Version 85.0.4183.102 (Official Build) (64-bit)
chrome-token-signing 0.0.30

**Comment by metsma** [comment]
I think the wording is wrong. If you are using signed binaries then it is this location. Updated wiki
