### ISSUE TITLE
mini.LECTOR-S doesnt work with few last versions

### ISSUE THREAD

**Issue by WoWce** [open-eid/chrome-token-signing#181]
We are using mini.LECTOR-S token to sign and it doesnt work with the last versions. I have build all the versions to find the last working version which is v1.0.7. 

EDIT: I did some digging and I found out that the commit: 757d8e3f4b68283c926ca0fced64a253120364b6 break the signing module. To be more precise it ends in condition if ((type & (NCRYPT_IMPL_HARDWARE_FLAG | NCRYPT_IMPL_REMOVABLE_FLAG)) == 0) where in my case type is 0. 

I dont know a lot about signing, but can someone explain why the case was changed? 

Thanks!

**Comment by metsma** [comment]
Project requires that Token is on Hardware device or smartcard.

**Comment by WoWce** [comment]
Well mini.LECTOR-S is hardware device which which contains token. Can you explain your answer more?

**Comment by metsma** [comment]
Then I wonder why the provider minidriver/CSP does not expose the hardware flags?
Can you provide some info about its middleware?

**Comment by WoWce** [comment]
About middleware? I am not sure where to get info about middleware.. Will this info help? https://prnt.sc/vgkqpe

**Comment by metsma** [comment]
Does device manager list "smart card reader" and "smart card" drivers?

**Comment by WoWce** [comment]
It list just "smart card reader". Took a screenshot. https://prnt.sc/vgl8kb

**Comment by metsma** [comment]
Hmm intresting can you produce logs with ole and new version of chrome token signing
https://github.com/open-eid/chrome-token-signing/wiki/DeveloperTips#logging

**Comment by WoWce** [comment]
[non-working version.txt](https://github.com/open-eid/chrome-token-signing/files/5516136/non-working.version.txt)
[working version.txt](https://github.com/open-eid/chrome-token-signing/files/5516139/working.version.txt)


Here are logs

**Comment by metsma** [comment]
I really don't know why this device claims that it is not hardware token.
Right now there is only solution to comment out the check.
Project scope is to only allow sign with hardware tokens.

**Comment by kristelmerilain** [comment]
Closing this issue because currently there are no plans to allow signing with software token.
