### ISSUE TITLE
The project lost  file jsonxx.cc

### ISSUE THREAD

**Issue by youngbug** [open-eid/chrome-token-signing#19]
I cannot find the file jsonxx.cc and jsonxx.h.

**Comment by allanjuhanson** [comment]
Hi youngbug 

Json parser that contains jsonxx.cc and jsonxx.h. is included as a [submodule](https://git-scm.com/docs/git-submodule) from [here](https://github.com/hjiang/jsonxx/tree/28bbb6bee2fdbb4fe633c29624564b73b2674795).

Probably when you cloned the repository, the submodule wasn't included. You need to add the `recursive` option when cloning.
`git clone https://github.com/open-eid/chrome-token-signing.git --recursive`

or when you already have the repository:
`git submodule update --init --recursive`

I hope this helps

**Comment by youngbug** [comment]
Thank you very much.

**Comment by allanjuhanson** [comment]
You're welcome
