### ISSUE TITLE
TokenSigning New version of Chrome Token Signing

### ISSUE THREAD

**Issue by tonytao34** [open-eid/chrome-token-signing#190]
I have an project with features like the project here: https://github.com/tonytao34/TokenSigning-
My tool called TokenSigning.
TokenSigning is the component (plugin) for web app to sign document with Usb Token, Smartcard,…
- TokenSigning not need Extension or add-on for browser
- TokenSigning supported: windows + macos
- TokenSigning supported all browsers: chrome, firefox, safari, ie, edge,....

**Comment by kristelmerilain** [comment]
Closing because this issue is not related to Chrome Token Signing.
