### ISSUE TITLE
When using Lithuanian eID, signature test fails if authentication certificate is selected

### ISSUE THREAD

**Issue by nesavonoru** [open-eid/chrome-token-signing#206]
https://hwcrypto.github.io/hwcrypto.js/sign.html

When using Lithuanian eID, signature test fails if authentication certificate is selected.
In the meantime signature test with signature certificate works as expected.

Environment: Windows 10 21H1, Microsoft Edge, smart card MW https://www.nsc.vrm.lt/files/pwpw_x64_v2_1_10.msi

**Comment by Counter178** [comment]
Related to #192 . Chrome token signing is only meant for signature.

**Comment by nesavonoru** [comment]
Thank you for the information.
I cannot register a new smart id account with Lithuanian eID at https://portal.smart-id.com/register
As stated in original post signing on https://hwcrypto.github.io/hwcrypto.js/sign.html works as expected...
It is hard to believe, however considering the information provided at https://www.id.ee/artikkel/ria-koos-partneritega-parandas-id-kaardi-brauserilaienduses-kriitilise-vea/ is it still possible that the service at https://portal.smart-id.com/register is not yet updated for the updated version of the browser plugin?
I have no other ideas what else could be wrong ...

**Comment by Counter178** [comment]
Hard to say. Would recommend contacting the service provider for clarified and better resolution https://www.smart-id.com/help/customer-service/ .
