### ISSUE TITLE
iPad OS 15 Safari Extension Support

### ISSUE THREAD

**Issue by WMRamadan** [open-eid/chrome-token-signing#209]
As of iPad OS 15 release, Safari for iPad/iOS now supports extensions.

Will the Safari Extension be ported over to iPad/iOS Safari Extensions?

**Comment by WMRamadan** [comment]
> For now seems like iOS does not support native messaging in web extensions which is critical for communicating smart card https://developer.apple.com/documentation/safariservices/sfsafariapplication/2823941-dispatchmessagewithname?language=objc

Should this then be done from the digidoc app, where the certificate is loaded by the app then whatever website requires the authentication it can be authenticated from that saved certificate?

I believe a similar workflow is done on https://pivkey.com/ which works by reading the certificate from a smart card reader and saves it on device then asks for a PIN when authenticating with the website.

If this is possible, would it represent any security concerns?

**Comment by metsma** [comment]
Seems like this is not using web extension. Instead there is now api to provide identity maybe through keychain.
It is similar to desktop how TLS authentication works.

**Comment by kristelmerilain** [comment]
Please open this issue in https://github.com/open-eid/MOPP-iOS.
