### ISSUE TITLE
Gemalto Token not working anymore / Restricting card/token by model?

### ISSUE THREAD

**Issue by tsmgodoi** [open-eid/chrome-token-signing#217]
Since the new version, the Gemalto Token can't sign hashes using the hwcrypto.js/webeid.js.
I've got a message saying: "Operation not supported. The card in the reader is not supported. Make sure that the engered ID-card is supported by the Web eID application."
Are you restricting card/token support by model? I want to confirm, because we use the Web eID solution outside Estonia to sign documents on an internal system. If so we need to think about new solutions/browser extensions.

**Comment by smartman** [comment]
You can still use older Chrome Token Signing instead of the Web eID for Gemalto Safenet eTokens. I have the same situation and even put together an install guide here https://eideasy.com/how-to-install-token-signing-extension-for-google-chrome/

**Comment by tsmgodoi** [comment]
@smartman, we're doing that for now. I'm asking here to know the future policy of the Open eID, so we can plan for it.

**Comment by tsmgodoi** [comment]
In Brazil we also use the following models:
- Watchkey (Watchdata)
- Etoken Pro (Safenet)
- GD Starsign (GD Burti)/StarSign Crypto Starsign CUT / S (GD)
- Etoken 5100 (Safenet)
- Etoken 5110 (Safenet)
- eToken Pro (Aladdin)
- Token Morphos (Morpho e-Documents)
If you could please add support for these. I'll research further if there are more.

**Comment by mrts** [comment]
A short update on our plans: we intend to add tier 3 support for Windows CryptoAPI tokens to Web eID in the coming weeks, but only for [cryptographic service providers (CSPs)](https://learn.microsoft.com/en-us/windows/win32/seccrypto/csps-and-the-cryptography-process) that support _Cryptography API: Next Generation_ (CNG). It should be sufficient for most current cards. If any cards have old drivers, we can raise the issue of supporting older CSPs separately later.

**Comment by mrts** [comment]
@tsmgodoi the first draft is available now from https://github.com/web-eid/web-eid-app/pull/231. You can download the binaries  or the installer from the last build of the pull request and experiment if your cards work as expected. **Please note that this is a draft, there may be bugs, it may crash, it does not report remaining PIN retries etc.**

**Comment by tsmgodoi** [comment]
It detected my token. I couldn't sign, though, because the field "Enter PIN2 for signing" doesn't allow special characters. And the SafeNet Authentication Client requires a password with special characters.
Could you please allow typing special characters on the PIN2 field?

**Comment by mrts** [comment]
Thank you for testing! The regular expression that limits input can be seen [here](https://github.com/web-eid/web-eid-app/blob/main/src/ui/webeiddialog.cpp#L479-L481). Can you please suggest what should the regular expression be?

**Comment by mrts** [comment]
@tsmgodoi, we changed the code so that it uses the external PIN entry dialog provided by the CSP driver as QSCD devices do not accept PIN input from external applications, so the special characters issue is off the table entirely now. You are very much invited to try if the latest build from https://github.com/web-eid/web-eid-app/pull/231 and give feedback if this looks good to you.

**Comment by tsmgodoi** [comment]
@mrts, I've tested it and it works like a charm now! Thank you for fulfilling our request. We really appreciate that.

**Comment by mrts** [comment]
The CryptoAPI work is now merged to main. Please report further issues and feature requests in the [web-eid-app project](https://github.com/web-eid/web-eid-app/issues).

**Comment by smartman** [comment]
> In Brazil we also use the following models:
> 
> * Watchkey (Watchdata)
> * Etoken Pro (Safenet)
> * GD Starsign (GD Burti)/StarSign Crypto Starsign CUT / S (GD)
> * Etoken 5100 (Safenet)
> * Etoken 5110 (Safenet)
> * eToken Pro (Aladdin)
> * Token Morphos (Morpho e-Documents)
>   If you could please add support for these. I'll research further if there are more.

@tsmgodoi which TSP is issuing certificates on these tokens? I would be happy to add support for these TSP-s and CA-s to eID Easy electronic signature marketplace also.

**Comment by tsmgodoi** [comment]
The certificates can be found here:
https://www.gov.br/iti/pt-br/assuntos/repositorio/repositorio-ac-raiz
The valid ones at the moment are:
[Certificado da AC Raiz da ICP-Brasil v2](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv2.crt)
[Certificado da AC Raiz da ICP-Brasil v4](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv4.crt)
[Certificado da AC Raiz da ICP-Brasil v5](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv5.crt)
[Certificado da AC Raiz da ICP-Brasil v6](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv6.crt)
[Certificado da AC Raiz da ICP-Brasil v7](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv7.crt)
[Certificado da AC Raiz da ICP-Brasil v10 - SSL](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv10.crt)
[Certificado da AC Raiz da ICP-Brasil v11 - Assinatura de Código](http://acraiz.icpbrasil.gov.br/credenciadas/RAIZ/ICP-Brasilv11.crt)
I'll lookup the TSP-s and post here later.
