### ISSUE TITLE
Fedora 25+ support?

### ISSUE THREAD

**Issue by plaes** [open-eid/chrome-token-signing#23]
Chromium browser is now officially included starting with Fedora 25: https://fedoraproject.org/wiki/Chromium

**Comment by martinpaljak** [comment]
If the component can be compiled successfully on Fedora, then packaging it should be a no-brainer. Maybe some file paths are different for Fedora than they are for Google versions on Ubuntu,  as described in https://github.com/open-eid/chrome-token-signing/wiki/Distribution

Any patches or wiki updates are most welcome.

**Comment by laurivosandi** [comment]
Estonian ID-card authentication works, slightly modified version of the following script needs to run first:
https://github.com/open-eid/linux-installer/blob/master/esteid-update-nssdb

**Comment by mihkelvain** [comment]
Review request: https://bugzilla.redhat.com/show_bug.cgi?id=1419715

**Comment by metsma** [comment]
For the project name confusion is very good explanation

https://blogs.gnome.org/ne0sight/2016/12/25/how-to-install-gnome-shell-extensions-with-firefox-52/
> You should not be confused by it’s name because chrome-gnome-shell supports all major browsers: Google Chrome/Chromium, Vivaldi, Opera and Firefox.
> 
> The words “for Chrome” in project’s name means “for Chrome extensions capable browsers” and recent versions of Firefox supports own implementation of “Chrome extensions API“: WebExtensions.
