### ISSUE TITLE
Signing fails with ridiculously long card reader name

### ISSUE THREAD

**Issue by laurivosandi** [open-eid/chrome-token-signing#25]
Hi,

finally took time to report the issue.

Running Chromium 53 on Ubuntu 16.04 here.

Certain HP keyboards have ridiculously long card names resulting in more than 100 characters. This causes Chrome plugin to go nuts when attempting to sign anything:

```
getCertificate()
VM149:8 Page received: 
VM149:9 Object {nonce: "mzwmh78ghbapwz1z", result: "technical_error", src: "background.js", extension: "0.0.22"}
```

A workaround is to substitute card reader name in pcscd driver database:

```bash
sed -i -e 's/Hewlett-Packard Company HP /HP /g' /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
service pcscd restart
```

A real fix probably should be implemented in the plugin itself by lifting card reader name size limitations or at least reserving 200 characters for the card reader name.

**Comment by metsma** [comment]
Fixed in commit aaf16a808e48d90856b1bada6018c623c6c396eb
