### ISSUE TITLE
Support for arbitrary smartcards

### ISSUE THREAD

**Issue by Glamdring** [open-eid/chrome-token-signing#3]
Currently the plugin doesn't work with arbitrary smart cards. Which is normal, because of the lack of standardization and openness of smartcard vendors.

For the purposes of reuse, however, it would be good to have some how-to and a clear way to add support for other smartcards. For example via adding a single file per smartcard type, which lists everything needed for the plugin to interact with the card (I'm hypothesizing here).

**Comment by metsma** [comment]
Windows works out of the box and for OSX/Linux there is ATR vs PKCS11 module mapping
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L107-L153
