### ISSUE TITLE
UX: do not restrict PIN/passphrase input, add a "show" button

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/chrome-token-signing#31]
Masking passphrase entry has been considered a not-so-great addition to actual password/passphrase security. Also, some (USB) tokens support/require alphanumeric passphrases instead of a numeric PIN.

OSX PIN input requires numbers. Instead of this restriction it would be better to add a "show PIN" button to reveal the input field while pressed, so that possible errors could be noticed.

**Comment by Telgat** [comment]
b2664ea5b5e872328ad14aee619a9533fe5a0c44
