### ISSUE TITLE
chrome-token-signing vs nativem-token-signing

### ISSUE THREAD

**Issue by user8547** [open-eid/chrome-token-signing#34]
"This Chrome extension allows you to sign documents on the web with your eID smart card."

Do I understand correctly that this extension is not anymore limited to Chrome?
Should the documentation be updated to reflect that? Maybe the repository name should also be changed to something like "nativem-token-signing"?

**Comment by Telgat** [comment]
The documentation has been updated https://github.com/open-eid/chrome-token-signing/blob/master/README.md
