### ISSUE TITLE
is Gemalto smartcard reader supported by chrome-token-signing extention ? 

### ISSUE THREAD

**Issue by guesmihela** [open-eid/chrome-token-signing#42]
I have a Gemalo smartCard reader and I install the extension in my chrome browser but there is no certificat list showed when I run it? I  don't know where is the problem??
can I use Gemalto smartCard reader  with chrome token signing? or it's not supported?

**Comment by vargaviktor** [comment]
you need to have add the pkcs11 drivers to the plugin to handle gemalto

**Comment by metsma** [comment]
You can add PKCS11 driver detection with ATR
https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11Path.cpp#L120
Windows CNG&CAPI drivers should be working out of the box
