### ISSUE TITLE
chrome-token-signin process should check whether stdin is not /dev/null

### ISSUE THREAD

**Issue by plaes** [open-eid/chrome-token-signing#5]
When accidentally starting chrome-token-signin process via window manager run dialog, process's stdin points to `/dev/null` and this causes process to run at 100% CPU.

Easiest way to test: `chrome-token-signing </dev/null`

Probably easiest way to fix it (assuming stdin only accepts input via pipes):

```
if (!isatty(fileno(stdin)) {
    // expecting stdin to be pipe
    exit(-1)
}
```

**Comment by martinpaljak** [comment]
This issue was moved to hwcrypto/hwcrypto-native#2
