### ISSUE TITLE
Problem with A3 certificate

### ISSUE THREAD

**Issue by AyrtonRicardo** [open-eid/chrome-token-signing#58]
Hello everyone,

I'm using a A3 certificate, but happens `techinical_error` after `getCertificate` with the message `Incompatible key`. I found this [CngCapiSigner.cpp](https://github.com/open-eid/chrome-token-signing/blob/1cc88c07f0960da6920a9fe87dd07e759842bea6/host-windows/CngCapiSigner.cpp#L135), but I don't know how to debug or test that problem, can anyone helps me?

OS: Windows 10
Type of certificate: Token(pen drive) A3

What library is this `CryptAcquireCertificatePrivateKey` ?

**Comment by metsma** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa379885%28v=vs.85%29.aspx

**Comment by AyrtonRicardo** [comment]
First, thanks for your fast feedback.

I'm seeing if it's some incompatibilities with brazilian certificates/tokens or just a problem with the user before close this issue.

**Comment by metsma** [comment]
Use certutil -v -scinfo for windows diagnostics

**Comment by AyrtonRicardo** [comment]
I'm debugging what's the problem, and I used the command `certutil -v -scinfo` in a certificate on my machine and I'm comparing with the certificate on the client. I read each single line and I'm not able to find any difference between both :cry: .

The message of the error is `Incompatible key`, exactly at [CngCapiSigner.cpp](https://github.com/open-eid/chrome-token-signing/blob/v1.0.5/host-windows/CngCapiSigner.cpp#L134) .

There's any knew issue using certificates of `https://support.globalsign.com/customer/en/portal/articles/1727343-download-and-install-ev-code-signing-certificate` ?

I've tested with more then 7 differents companies but I'm not able to reproduce the error, only with client and this company the error appears.

**Comment by AyrtonRicardo** [comment]
I saw my error while debugging this issue, probably fixed in release `1.0.6`. I'll test it and I'll be sure.

**Comment by AyrtonRicardo** [comment]
@metsma thanks for you help. My problem was fixed on [Release 1.0.6](https://github.com/open-eid/chrome-token-signing/releases/tag/v1.0.6-beta). 

Thanks a lot and good job man!
