### ISSUE TITLE
chrome-token-signing using 100% of CPU without any browser running or smartcard attached

### ISSUE THREAD

**Issue by vprints** [open-eid/chrome-token-signing#59]
![screenshot_20170803_154805](https://user-images.githubusercontent.com/5511746/28922747-1111b83c-7864-11e7-9229-cec1a920b30e.png)

On startup in Ubuntu 16.10

**Comment by metsma** [comment]
Maybe browser closed by unatural causes and native host left running?
By default if you close browser native host will be closed

**Comment by metsma** [comment]
No response 3 weeks, closing for now. Reopen if it is needed
