### ISSUE TITLE
Remove OpenSSL dependency in host-shared

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/chrome-token-signing#6]
OSX 10.11 and later remove OpenSSL headers from the system and encourage the usage of OSX specific interfaces.

Currently host-osx makes use of the shared component for PKCS#11, which in turn makes use of OpenSSL for certificate parsing, like here:

https://github.com/open-eid/chrome-token-signing/blob/master/host-shared/PKCS11CardManager.h#L127

Refactor this to either remove OpenSSL, isolate it with ifdefs or move the necessary filtering and parsing to the host-osx part.

**Comment by martinpaljak** [comment]
This means that building it is currently not possible on the latest, 10.12.

**Comment by martinpaljak** [comment]
https://developer.apple.com/reference/security/1396051-seccertificatecopyvalues ?

**Comment by Telgat** [comment]
530fee485b598c9e15f078819b22a765eb9b313d
