### ISSUE TITLE
Firefox 58 support seems broken in Linux

### ISSUE THREAD

**Issue by hsanjuan** [open-eid/chrome-token-signing#80]
I have successfully compiled and installed the extension and the `chrome-token-signing` tool in my system (OpenSUSE 42.3). The Token signing extension is listed in Firefox and the `chrome-token-signing` application can be executed in the command line and doesn't error (digicert application is also installed).

However, the `hwcrypto.js` still fails to make use of the installed extension (even though it sees it, I think check/test fails though).

In Google Chrome, though, things work well (after running `./esteid-update-nssdb` from the installer at least) and I can sign documents online.

Is there anything I can do to have this working in Firefox too?

**Comment by metsma** [comment]
Can you enable logging and send logs

https://github.com/open-eid/chrome-token-signing/wiki/DeveloperTips#logging

**Comment by hsanjuan** [comment]
@metsma do you know if there is there a test site somewhere for signing stuff? digidoc.ee complains about `Please enable browser plugin and refresh this page.` even though the token signing plugin is listed in the Firefox addons.

**Comment by hsanjuan** [comment]
OK I found https://hwcrypto.github.io/demo/

It doesn't seem to detect the extension: `Debug: hwcrypto.js 0.0.11 with failing backend Chrome native messaging extension`

**Comment by metsma** [comment]
I use this https://hwcrypto.github.io/hwcrypto.js/sign.html

**Comment by hsanjuan** [comment]
I found the issue, the native messaging manifest `ee.ria.esteid.json` file is instaled in `/usr/lib/mozilla/native-messaging-hosts` and not in `/usr/lib64/mozilla/native-messaging-hosts`.

**Comment by hsanjuan** [comment]
Related PR #83

**Comment by Germano0** [comment]
> I found the issue, the native messaging manifest ee.ria.esteid.json file is instaled in /usr/lib/mozilla/native-messaging-hosts and not in /usr/lib64/mozilla/native-messaging-hosts.

@hsanjuan I was experiencing the same trouble https://github.com/open-eid/linux-installer/issues/13#issuecomment-371574600
and I solved with your instructions. Thank you very much, now I am able to fix the Fedora package!

**Comment by metsma** [comment]
Can you test #100 where you can customize path
`make LIBPATH=/usr/lib64`

**Comment by Germano0** [comment]
> Can you test #100 where you can customize path
> make LIBPATH=/usr/lib64

Actually it does not work. But wait my next feedback during next week. I want to better investigate if I made some mistakes in the spec file

[build logs](https://koji.fedoraproject.org/koji/taskinfo?taskID=25733909)
[Fedora package tree](https://src.fedoraproject.org/rpms/webextension-token-signing/tree/f27)

**Comment by kkofler** [comment]
See https://github.com/open-eid/chrome-token-signing/pull/100#issuecomment-373963428 for why it does not work.

**Comment by Germano0** [comment]
> See #100 (comment) for why it does not work.

Thank you Kevin. I will wait for a new comment or patch from @metsma

**Comment by metsma** [comment]
Fixed by 5161fd400c424f09f30b70ba3125c26924848536
