### ISSUE TITLE
Firefox extension on Mozilla addons site

### ISSUE THREAD

**Issue by abitrolly** [open-eid/chrome-token-signing#93]
There is no extension at Mozilla's site. Why not to add it there?

https://addons.mozilla.org/en-US/firefox/search/?q=open-eid&type=extension

**Comment by metsma** [comment]
https://github.com/open-eid/chrome-token-signing/blob/master/%7B443830f0-1fff-4f9a-aa1e-444bafbc7319%7D.xpi

**Comment by abitrolly** [comment]
@metsma how to discover and install it directly from Firefox? Like https://addons.mozilla.org/en-US/firefox/addon/belgium-eid/

**Comment by metsma** [comment]
I dont understand. Belgium does not provide Signing solutions

**Comment by abitrolly** [comment]
@metsma it is not about signing solutions - it is about how to install the extension through standard Firefox way - [about:addons](about:addons) page.

**Comment by metsma** [comment]
It does not work without other components. Why make things complicated to users?
Install whole working solution with one installer/package.
No need install somme components from package and some from store.

**Comment by abitrolly** [comment]
@metsma it can guide people what components are required. This will provide a better experience for e-residents. For other Firefox users who are browsing available addons it will help to discover e-Residency.

**Comment by metsma** [comment]
For chrome-token-signing is required /usr/bin/chrome-token-signing binary
Chrome:
* /opt/google/chrome/extensions/ckjefchnfjhjfedoccjbhjpbncimppeg.json to force install extension from store
* /etc/opt/chrome/native-messaging-hosts/ee.ria.esteid.json to give chrome extension permission to use chrome-token-signing binary
Firefox:
* /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{443830f0-1fff-4f9a-aa1e-444bafbc7319}.xpi to install extension globally to all users
* /usr/lib/mozilla/native-messaging-hosts/ee.ria.esteid.json to give firefox extension permission to use chrome-token-signing binary
